In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import pickle
from ydata_profiling import ProfileReport

In [3]:
df = pd.read_csv('Advertising.csv')

In [5]:
df

ID     TV  Radio  Newspaper  Sales
0      1  230.1   37.8       69.2   22.1
1      2   44.5   39.3       45.1   10.4
2      3   17.2   45.9       69.3    9.3
3      4  151.5   41.3       58.5   18.5
4      5  180.8   10.8       58.4   12.9
..   ...    ...    ...        ...    ...
195  196   38.2    3.7       13.8    7.6
196  197   94.2    4.9        8.1    9.7
197  198  177.0    9.3        6.4   12.8
198  199  283.6   42.0       66.2   25.5
199  200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [9]:
df.head(10)

ID     TV  Radio  Newspaper  Sales
0   1  230.1   37.8       69.2   22.1
1   2   44.5   39.3       45.1   10.4
2   3   17.2   45.9       69.3    9.3
3   4  151.5   41.3       58.5   18.5
4   5  180.8   10.8       58.4   12.9
5   6    8.7   48.9       75.0    7.2
6   7   57.5   32.8       23.5   11.8
7   8  120.2   19.6       11.6   13.2
8   9    8.6    2.1        1.0    4.8
9  10  199.8    2.6       21.2   10.6

In [13]:
df.shape

(200, 5)

In [15]:
df.describe()

ID          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [17]:
df.isnull().sum()

ID           0
TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [20]:
report = ProfileReport(df)

In [22]:
report

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [24]:
report.to_widgets()

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [26]:
report.to_file('test.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [35]:
df.columns

Index(['ID', 'TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [28]:
x = df[['TV']]

In [30]:
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [37]:
y = df[['Sales']]

In [39]:
y

Sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

In [41]:
from sklearn.linear_model import LinearRegression

In [45]:
Model = LinearRegression()

In [47]:
Model.fit(x,y)

LinearRegression()

In [49]:
Model.intercept_

array([7.03259355])

In [53]:
Model.coef_

array([[0.04753664]])

In [55]:
Model.predict([[45]])

C:\Users\SARVESH SAPKALE\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[9.17174237]])

In [57]:
l = [4,5,6,7,89,34,45,67,23]

In [61]:
for i in l:
    print(Model.predict([[i]]))

[[7.22274011]]
[[7.27027675]]
[[7.31781339]]
[[7.36535003]]
[[11.26335455]]
[[8.64883932]]
[[9.17174237]]
[[10.21754846]]
[[8.12593628]]


C:\Users\SARVESH SAPKALE\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\SARVESH SAPKALE\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\SARVESH SAPKALE\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\SARVESH SAPKALE\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\SARVESH SAPKALE\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\SARVESH SAPKALE\anaconda3\Lib\s

In [63]:
Model.score(x,y)

0.611875050850071